name: topical-feed

on:
  schedule:
    - cron: '0 1/4 * * *'
  workflow_dispatch:

# to consider: the use of action jobs to breakout each task
# https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs

env:
  LANG: "fr_FR.UTF-8"

jobs:
  run-cyberwatch:
    runs-on: ubuntu-latest
    timeout-minutes: 170
    environment: CI
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: fr_FR.UTF-8
        run: |
          sudo locale-gen fr_FR.UTF-8
          sudo update-locale LANG=fr_FR.UTF-8
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Generate RSS Feed
        run: |
          python3 LeMagIT-cybersecurite-rss.py
      - name: Save changes
        run: |  
          DATE=$(date -Iseconds)
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git pull origin main
          git commit --all --message "Updated by Crontab on $DATE" || echo "no changes to commit" 
          git push origin main
